### ISSUE TITLE
Save not working in Firefox for Android?

### ISSUE THREAD

**Issue by GollyJer** [archy-bold/wordle-archive#1]
Hey! Was trying to migrate today. Thanks for the great code!

I created the bookmarks. They both run fine in Firefox desktop and the Restore code runs in Firefox for Android, but nothing happens when running the Save script. 

Not sure how to troubleshoot. Thought I'd post here just to see if there's an easy answer.

Best!
Jeremy

**Comment by archy-bold** [comment]
Hi there Jeremy. Looks like there are issues with [bookmarklets in Firefox for Android](https://github.com/mozilla-mobile/fenix/issues/2871). According to that issue it seems as though they were fixed and then the fix was removed due to conflicting issues.

I've seen similar in Chrome on Android. Basically opening the bookmarks page opens a new tab and the bookmarklet gets run on the bookmarks page, not on the Wordle page; hence why nothing happens. The workaround for Chrome was to use the address bar to search for the bookmark and run it from the address bar, which would execute the code on the open page. Firefox, however, seems to effectively open a new tab every time you click the address bar, meaning there's no way to run that code in the open tab. I even tried pasting the code directly in the address bar and it just searched Google.

It might be that the problem will be fixed in an upcoming Firefox release, but the fact that it was reverted shows it's not an easy problem to fix so that could be a long wait.

But you do have options:

1. The save state is saved in javascript `localStorage`, so you could find another way to transfer that. [This page](https://support.mozilla.org/bm/questions/1263477) discusses how to transfer Firefox user profiles, which might work.
2. Make a note of your stats and manually edit the json with them. Basically the way this code works is it takes the stats and game state as json, then encodes it with base64. I did this just so people couldn't try to tweak their stats, break it and complain something wasn't working! There are plenty of [online tools to encode/decode in base64](https://www.base64decode.org/). At the bottom I've pasted my stats from today **(watch out, today's solution is in there too)**. You could just edit the `statistics` section of that with your stats and encode it with base64. That should give you a valid save string to use in the restore popup. If you attempt this on another day, I recommend getting your own copy of the json by playing the day's game on a device where the save state bookmarket works, run the bookmarklet and base64 decode the save string; that way you'll have the actual day's word in the game state section of the json.

**Note:** While it might seem like the restore bookmarklet is working on Android Firefox, it's unlikely that it will work when you actually paste a save string in there as it won't run the code on the open Wordle page. If you want to move your Wordle save around, maybe Firefox for Android isn't the browser to play the game in.

Let me know if you have any other issues with it, but there's not much I can do on the code, unfortunately.

```json
{"gameState":{"boardState":["","","","","",""],"evaluations":[null,null,null,null,null,null],"rowIndex":0,"solution":"shine","gameStatus":"IN_PROGRESS","lastPlayedTs":1652082575747,"lastCompletedTs":1652000287542,"restoringFromLocalStorage":null,"hardMode":false},"statistics":{"currentStreak":131,"maxStreak":131,"guesses":{"1":0,"2":8,"3":52,"4":55,"5":16,"6":0,"fail":0},"winPercentage":100,"gamesPlayed":131,"gamesWon":131,"averageGuesses":4}}
```

**Comment by GollyJer** [comment]
Got it. Thanks!

**Comment by czlucius** [comment]
> with [bookmarklets in Firefox for Android](https://github.com/mozilla-mobile/fenix/issues/2871). According to that issue it seems as though they were fixed and then the fix was removed due to conflicting issues.

Another patch was merged shortly after, and is in Stable right now. 
The issue should be fixed (needs testing).
Thanks

**Comment by archy-bold** [comment]
Thanks for the heads up @czlucius!
